using System;
using System.Collections.Generic;
using System.Text;

namespace Server.Mobiles
{
    public enum DonEnum
    {
        //Dons de classe
        RageBerserker,

        //Dons généraux
        AffiniteMagique = 1000,
        AmeliorationDesCreaturesConvoquees,
        ArmeDePredilection,
        ArmeDePredilectionSuperieure,
        ArmeEnMain,
        Athletisme,
        AttaqueAuGalop,
        AttaqueEclair,
        AttaqueEnFinesse,
        AttaqueEnPuissance,
        AttaqueEnRotation,
        AttaquesReflexes,
        Autonome,
        ChargeDevastatrice,
        CombatADeuxArmes,
        CombatEnAveugle,
        CombatMonte,
        CoupEtourdissant,
        Course,
        DefenseADeuxArmes,
        Discret,
        DispenseDeComposantsMateriels,
        DoigtsDeFee,
        DurACuire,
        EcoleRenforcee,
        EcoleSuperieure,
        EfficaciteDesSortsAccrue,
        EfficaciteDesSortsSuperieure,
        EmpriseSurLesMortsVivants,
        Enchainement,
        Endurance,
        Esquive,
        ExpertiseDuCombat,
        FeuNourri,
        FinLimier,
        Fourberie,
        FraterniteAnimale,
        Funambule,
        IncantationAnimale,
        InterceptionDeProjectile,
        MagieDeGuerre,
        MaitriseDesSorts,
        MaitriseDuCombatADeuxArmes,
        ManiementUneArmeDeGuerre,
        ManiementUneArmeEotique,
        ManiementDesArmesCourantes,
        ManiementDesBoucliers,
        ManiementDuPavois,
        Meticuleux,
        Negociation,
        ParadeDeProjectiles,
        Persuasion,
        Pietinement,
        Pistage,
        PortDesArmuresIntermediaires,
        PortDesArmuresLegeres,
        PortDesArmuresLourdes,
        Prestige,
        RechargementRapide,
        ReflexesSurhumains,
        Robustesse,
        SavoirFaireMecanique,
        ScienceDeLaDestruction,
        ScienceDeInitiative,
        ScienceDeLaBousculade,
        ScienceDeLaFeinte,
        ScienceDeLaLutte,
        ScienceDuCombatADeuxArmes,
        ScienceDuCombatAMainsNues,
        ScienceDuContresort,
        ScienceDuCoupDeBouclier,
        ScienceDuCritique,
        ScienceDuCrocEnJambe,
        ScienceDuDesarmement,
        ScienceDuRenversement,
        ScienceDuRenvoi,
        ScienceDuTirDePrecision,
        SouplesseDuSerpent,
        SpecialisationMartiale,
        SpecialisationMartialeSuperieure,
        SuccessionEnchainements,
        Talent,
        TirABoutPortant,
        TirDeLoin,
        TirDePrecision,
        TirEnMouvement,
        TirMonte,
        TirRapide,
        Vigilance,
        VigueurSurhumaine,
        VolonteDeFer,
        Voltigeur,

        Maximum
    }
}
