using System;
using System.Collections.Generic;
using System.Text;

namespace Server.Mobiles
{
    public enum DonEnum
    {
        //Dons de classe

        //Barbare
        DonSupClasse = 0,
        RageBerserker,
        EsquiveInstinctive, //+Esquive instinctive supérieur (rang2)
        SensPieges,
        ReductionDegat,
        RageGrandBerserker,
        VolonteIndomptable,
        RageSansFatigue,
        RageMaitreBerserker,
        //Barde
        ContreChant,
        InspirationVaillante,
        InspirationTalent,
        InspirationHero,
        ChantLiberte,
        InspirationIntrepide,
        //Moine
        DelugeCoup,
        EsquiveTotale,
        Serenite,
        FrappeKi,
        PuretePhysique,
        PlenitudePhysique,
        CorpDiamant,
        SautAmeliore,
        AmeDiamant,
        JeunesseEternelle,
        PerfectionEtre,
        //Roublard
        AttaqueSournoise,
        RecherchePiege,

        //Dons généraux
        DonSupGeneral = 1000,
        AffiniteMagique,
        AmeliorationDesCreaturesConvoquees,
        ArmeDePredilection,
        ArmeDePredilectionSuperieure,
        ArmeEnMain,
        Athletisme,
        AttaqueAuGalop,
        AttaqueEclair,
        AttaqueEnFinesse,
        AttaqueEnPuissance,
        AttaqueEnRotation,
        AttaquesReflexes,
        Autonome,
        ChargeDevastatrice,
        CombatADeuxArmes,
        CombatEnAveugle,
        CombatMonte,
        CoupEtourdissant,
        Course,
        DefenseADeuxArmes,
        Discret,
        DispenseDeComposantsMateriels,
        DoigtsDeFee,
        DurACuire,
        EcoleRenforcee,
        EcoleSuperieure,
        EfficaciteDesSortsAccrue,
        EfficaciteDesSortsSuperieure,
        EmpriseSurLesMortsVivants,
        Enchainement,
        Endurance,
        Esquive,
        ExpertiseDuCombat,
        FeuNourri,
        FinLimier,
        Fourberie,
        FraterniteAnimale,
        Funambule,
        IncantationAnimale,
        InterceptionDeProjectile,
        MagieDeGuerre,
        MaitriseDesSorts,
        MaitriseDuCombatADeuxArmes,
        ManiementUneArmeDeGuerre,
        ManiementUneArmeEotique,
        ManiementDesArmesCourantes,
        ManiementDesBoucliers,
        ManiementDuPavois,
        Meticuleux,
        Negociation,
        ParadeDeProjectiles,
        Persuasion,
        Pietinement,
        Pistage,
        PortDesArmuresIntermediaires,
        PortDesArmuresLegeres,
        PortDesArmuresLourdes,
        Prestige,
        RechargementRapide,
        ReflexesSurhumains,
        Robustesse,
        SavoirFaireMecanique,
        ScienceDeLaDestruction,
        ScienceDeInitiative,
        ScienceDeLaBousculade,
        ScienceDeLaFeinte,
        ScienceDeLaLutte,
        ScienceDuCombatADeuxArmes,
        ScienceDuCombatAMainsNues,
        ScienceDuContresort,
        ScienceDuCoupDeBouclier,
        ScienceDuCritique,
        ScienceDuCrocEnJambe,
        ScienceDuDesarmement,
        ScienceDuRenversement,
        ScienceDuRenvoi,
        ScienceDuTirDePrecision,
        SouplesseDuSerpent,
        SpecialisationMartiale,
        SpecialisationMartialeSuperieure,
        SuccessionEnchainements,
        Talent,
        TirABoutPortant,
        TirDeLoin,
        TirDePrecision,
        TirEnMouvement,
        TirMonte,
        TirRapide,
        Vigilance,
        VigueurSurhumaine,
        VolonteDeFer,
        Voltigeur,

        Maximum
    }
}
